[project]
name = "discord-catchup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "inquirerpy>=0.3.4",
    "pydantic-settings>=2.8.1",
    "pydantic>=2.10.6",
    "pynacl>=1.5.0",
]
